### ISSUE TITLE
Make touchID public

### ISSUE THREAD

**Issue by BBUK** [DustinWatts/FT6236#12]
Thanks for the great library.  

A small suggestion - the touch ID is really useful to have available from user code.  The reasoning being is that when there are two touches, each may be put into the IC's 1st touch register or the 2nd touch register seemingly at random as the two fingers are moved around (the IC just does this, it is not a problem with your library).  The touch ID is, however, consistent.  Using the touch ID, it becomes easy to work out whether the data in the 1st touch register or the 2nd touch register really represents the first or second touch.  It tells you which of the registers are reporting which finger.

The first finger to be touched will have a touch ID of zero, and it will stay as zero as long as the finger touches the screen.  Similarly with the second finger to be touched, except it will have a touch ID of 1.  Each point read from your library has a touch ID associated with it, this will tell you whether the XY position in the registers is associated with the first finger or the second.

Also, when there is a touch with one finger, then a second (so two touches) and then the first is released, the two touch IDs for the registers operate as follows:

0 15 (first finger down, 15 is no touch)
0 1 (second finger down, this could also flip back and forth to 1 0 at random, depending on which registers are reporting which finger)
1 15 (first finger lifted but the 1st touch register is now reporting the position of the second finger to touch the screen)

All that is needed to make the touch ID available from user code is to move the touchID[2] array to the public section of the class definition.  Not worth creating a PR for!

Thanks again

**Comment by DustinWatts** [comment]
Sure... this is not a major change in the repo. I'll see when I have time to do this :)

**Comment by DustinWatts** [comment]
Seems I had some time now ;)

92fb1c4
