### ISSUE TITLE
Multitouch or gestures?

### ISSUE THREAD

**Issue by kmatch98** [DustinWatts/FT6236#2]
I’ve got a display with the 6206 version of this chip but I can’t seem to extract more than a single touch. 

The datasheet mentions multitouch capability and gesture detection. Do you have any experience getting multiple touches or gestures from your touch display with the FT6236 chip?

**Comment by DustinWatts** [comment]
Hi! I'm sorry I missed this issue! 

Although the datasheet says there are gestures available (it also has a register for it) it seems they are not available on this IC.
