### ISSUE TITLE
Origin of FT6236 vs ILI9488

### ISSUE THREAD

**Issue by bradanlane** [DustinWatts/FT6236#4]
Am I correct the the 0,0 origin used for FT6236 TS_Point is lower left while the origin of the display is upper left?

**Comment by DustinWatts** [comment]
It depends on how you hold the screen of course... but for example on the ESP32 TouchDown, if the USB is upper right, the origin is lower left. 

On the ILI9488 it depends on the rotation set via the library. So on the screen the origin can change, but on the FT62x6 it is fixed. So if you rotated the screen (in software) you will have to map the X/Y of the touch to the screen.

**Comment by bradanlane** [comment]
Good point. I added an "origin" option to the code so it's easier to have the FT62x6 match the display. I also added a mapping to address the physical dimensions of the FT62x6 vs the pixel area of the display.
