### ISSUE TITLE
 FT6236  versus Adafruit_FT6206 Library

### ISSUE THREAD

**Issue by DonpK** [DustinWatts/FT6236#5]
I am working with the [EastRising 3.5" TFT-LCD display](https://www.buydisplay.com/lcd-3-5-inch-320x480-tft-display-module-optl-touch-screen-w-breakout-board) which uses the FT6236 capacitive touch controller and ILI9488 display library. 

I have been using the Adafruit_FT6206 Library which Adafruit says "[Also supports FT6236 chips (and maybe other compatible chips!)](https://github.com/adafruit/Adafruit_FT6206_Library)".  Generally this Adafruit FT6206 library is working okay with the EastRising display, although I am having one problem.

Have you used your FT6236 library with the East Rising 3.5" display? What, if any, differences are there between your FT6236 library and the Adafruit FT6206 library?

Thanks,
    Don

**Comment by DonpK** [comment]
@DustinWatts 
After installing the FT6236 library a compile error is generated. I've attached a text copy. Any thoughts?
[FT6236 Compile Error Messages.txt](https://github.com/DustinWatts/FT6236/files/7069889/FT6236.Compile.Error.Messages.txt)

**Comment by DustinWatts** [comment]
I see what is happening. This library is not for ATmega boards.....

You could replace this in FT6236.cpp:
```
if (sda != -1 && scl != -1)
    {
        Wire.begin(sda, scl);
    }
    else
    {
        Wire.begin();
    }
```
by:
```
        Wire.begin();
```
Basically removing the while if-statement that gives you the option to set a custom I2C pins, which is not supported by the I2C library for ATmega boards.

**Comment by DustinWatts** [comment]
A long time not activity here so I'm closing it. Feel free to reopen.
