### ISSUE TITLE
Example Pin Assignments

### ISSUE THREAD

**Issue by PlastiBots** [DustinWatts/FT6236#6]
Hi. Thanks for providing this library.  In your example, you note the below.  Can you clarify what the first # is for in the pin assignments below (40)?  Is it the Touch Interrupt pin #?

`//begin(40, SDA, SCL) for custom pins`

**Comment by DustinWatts** [comment]
Hi @PlastiBots Yes I can clarify. It is the sensitivity of the touch controller.

I will put a note in the code!

**Comment by PlastiBots** [comment]
That's helpful. Thanks!
